// NSE symbol → real logo file (public/stock-logos/), same two-tier fallback as bankLogos.ts:
// real file → colored monogram (brand-adjacent hex + initials) → generic PremiumIcon badge.
// No real files curated yet (see StockLogo.tsx) — this map exists now so dropping files into
// public/stock-logos/ later is a pure data change, no component change. Hex values here are
// brand-adjacent approximations, not verified trademark colors — same rigor as BANK_MONOGRAMS
// in bankLogos.ts, good enough for a small colored badge, not meant to be pixel-exact.
const REAL_LOGO_FILES: Record<string, string> = {};

export function getRealStockLogoFile(symbol?: string): string | undefined {
  if (!symbol) return undefined;
  return REAL_LOGO_FILES[symbol.trim().toUpperCase()];
}

export interface StockMonogram { initials: string; hex: string; }

// Nifty 50 constituents plus a handful of other commonly-held NSE names. Deliberately not
// exhaustive (NSE lists ~2,400 symbols) — anything missing here just falls through to the
// generic stock icon, same as every symbol did before this file existed.
const STOCK_MONOGRAMS: Record<string, StockMonogram> = {
  RELIANCE:    { initials: "RIL",    hex: "#002E6D" },
  TCS:         { initials: "TCS",    hex: "#0B3861" },
  HDFCBANK:    { initials: "HDFC",   hex: "#E31E24" },
  INFY:        { initials: "INFY",   hex: "#007CC3" },
  ICICIBANK:   { initials: "ICICI",  hex: "#F58220" },
  HINDUNILVR:  { initials: "HUL",    hex: "#0033A0" },
  ITC:         { initials: "ITC",    hex: "#A6192E" },
  SBIN:        { initials: "SBI",    hex: "#2A5DB0" },
  BHARTIARTL:  { initials: "AIRTEL", hex: "#ED1C24" },
  KOTAKBANK:   { initials: "KOTAK",  hex: "#ED1C24" },
  LT:          { initials: "L&T",    hex: "#002C6C" },
  AXISBANK:    { initials: "AXIS",   hex: "#97144D" },
  ASIANPAINT:  { initials: "AP",     hex: "#ED1C24" },
  MARUTI:      { initials: "MSIL",   hex: "#E4002B" },
  TITAN:       { initials: "TITAN",  hex: "#B08D57" },
  SUNPHARMA:   { initials: "SUN",    hex: "#F58220" },
  ULTRACEMCO:  { initials: "UTCEM",  hex: "#E30613" },
  NESTLEIND:   { initials: "NESTLE", hex: "#78BE20" },
  WIPRO:       { initials: "WIPRO",  hex: "#341F65" },
  BAJFINANCE:  { initials: "BAJAJ",  hex: "#003876" },
  HCLTECH:     { initials: "HCL",    hex: "#0075C9" },
  TATAMOTORS:  { initials: "TATA",   hex: "#0B3861" },
  TATASTEEL:   { initials: "TATA",   hex: "#0B3861" },
  TATACONSUM:  { initials: "TATA",   hex: "#0B3861" },
  ADANIENT:    { initials: "ADANI",  hex: "#E31E24" },
  ADANIPORTS:  { initials: "ADANI",  hex: "#E31E24" },
  POWERGRID:   { initials: "PGCIL",  hex: "#0033A0" },
  NTPC:        { initials: "NTPC",   hex: "#0054A6" },
  ONGC:        { initials: "ONGC",   hex: "#EE2E24" },
  COALINDIA:   { initials: "CIL",    hex: "#33383D" },
  JSWSTEEL:    { initials: "JSW",    hex: "#E31E24" },
  GRASIM:      { initials: "GRASIM", hex: "#0B3861" },
  HINDALCO:    { initials: "HDLC",   hex: "#0B3861" },
  DRREDDY:     { initials: "DRL",    hex: "#00563F" },
  CIPLA:       { initials: "CIPLA",  hex: "#EE2E24" },
  DIVISLAB:    { initials: "DIVIS",  hex: "#003DA5" },
  EICHERMOT:   { initials: "EICHER", hex: "#C8102E" },
  HEROMOTOCO:  { initials: "HERO",   hex: "#E4002B" },
  "BAJAJ-AUTO":{ initials: "BAJAJ",  hex: "#003876" },
  "M&M":       { initials: "M&M",    hex: "#E31E24" },
  BRITANNIA:   { initials: "BRIT",   hex: "#ED1C24" },
  TECHM:       { initials: "TECHM",  hex: "#E31E24" },
  SBILIFE:     { initials: "SBI",    hex: "#2A5DB0" },
  HDFCLIFE:    { initials: "HDFC",   hex: "#E31E24" },
  BAJAJFINSV:  { initials: "BAJAJ",  hex: "#003876" },
  APOLLOHOSP:  { initials: "APOLLO", hex: "#ED1C24" },
  INDUSINDBK:  { initials: "IIB",    hex: "#A6192E" },
  UPL:         { initials: "UPL",    hex: "#0033A0" },
  VEDL:        { initials: "VEDL",   hex: "#E31E24" },
  GAIL:        { initials: "GAIL",   hex: "#F58220" },
  IOC:         { initials: "IOCL",   hex: "#F58220" },
  BPCL:        { initials: "BPCL",   hex: "#F58220" },
  ZOMATO:      { initials: "ZOM",    hex: "#E23744" },
  PAYTM:       { initials: "PAYTM",  hex: "#00BAF2" },
  IRCTC:       { initials: "IRCTC",  hex: "#003DA5" },
  DMART:       { initials: "DMART",  hex: "#00A651" },

  // Nifty Next 50 / other large- and mid-caps commonly held beyond the Nifty 50 set above
  PIDILITIND:  { initials: "PIDI",   hex: "#003DA5" },
  SIEMENS:     { initials: "SIE",    hex: "#009999" },
  DLF:         { initials: "DLF",    hex: "#ED1C24" },
  GODREJCP:    { initials: "GCPL",   hex: "#00563F" },
  HAVELLS:     { initials: "HAV",    hex: "#ED1C24" },
  AMBUJACEM:   { initials: "AMB",    hex: "#F58220" },
  BANKBARODA:  { initials: "BOB",    hex: "#F58220" },
  PNB:         { initials: "PNB",    hex: "#7A1F2B" },
  CANBK:       { initials: "CBK",    hex: "#003DA5" },
  UNIONBANK:   { initials: "UBI",    hex: "#003DA5" },
  IDFCFIRSTB:  { initials: "IDFC",   hex: "#A6192E" },
  FEDERALBNK:  { initials: "FB",     hex: "#002D72" },
  YESBANK:     { initials: "YES",    hex: "#003DA5" },
  AUBANK:      { initials: "AU",     hex: "#ED1C24" },
  BANDHANBNK:  { initials: "BDN",    hex: "#A6192E" },
  PFC:         { initials: "PFC",    hex: "#0033A0" },
  RECLTD:      { initials: "REC",    hex: "#0033A0" },
  IRFC:        { initials: "IRFC",   hex: "#003DA5" },
  LICI:        { initials: "LIC",    hex: "#00563F" },
  ICICIGI:     { initials: "ICICI",  hex: "#F58220" },
  ICICIPRULI:  { initials: "ICICI",  hex: "#F58220" },
  MAXHEALTH:   { initials: "MAX",    hex: "#ED1C24" },
  FORTIS:      { initials: "FRT",    hex: "#00A651" },
  LUPIN:       { initials: "LUPIN",  hex: "#EE2E24" },
  AUROPHARMA:  { initials: "AURO",   hex: "#003DA5" },
  ALKEM:       { initials: "ALKM",   hex: "#00563F" },
  TORNTPHARM:  { initials: "TORNT",  hex: "#ED1C24" },
  MANKIND:     { initials: "MANK",   hex: "#00A651" },
  ZYDUSLIFE:   { initials: "ZYD",    hex: "#003DA5" },
  BIOCON:      { initials: "BIOCON", hex: "#00A651" },
  COLPAL:      { initials: "CP",     hex: "#ED1C24" },
  DABUR:       { initials: "DABUR",  hex: "#ED1C24" },
  MARICO:      { initials: "MRCO",   hex: "#003DA5" },
  GODFRYPHLP:  { initials: "GPI",    hex: "#7A1F2B" },
  VBL:         { initials: "VBL",    hex: "#ED1C24" },
  UNITDSPR:    { initials: "USL",    hex: "#003876" },
  BAJAJHLDNG:  { initials: "BAJAJ",  hex: "#003876" },
  CHOLAFIN:    { initials: "CHOLA",  hex: "#ED1C24" },
  MUTHOOTFIN:  { initials: "MUT",    hex: "#ED1C24" },
  LTF:         { initials: "LTF",    hex: "#002C6C" },
  LTIM:        { initials: "LTIM",   hex: "#002C6C" },
  PERSISTENT:  { initials: "PERS",   hex: "#003DA5" },
  COFORGE:     { initials: "COFO",   hex: "#00563F" },
  MPHASIS:     { initials: "MPH",    hex: "#003DA5" },
  OFSS:        { initials: "OFSS",   hex: "#F80000" },
  NAUKRI:      { initials: "INFOE",  hex: "#4E4EF5" },
  POLICYBZR:   { initials: "PB",     hex: "#00BFB3" },
  NYKAA:       { initials: "NYKAA",  hex: "#FC2779" },
  DELHIVERY:   { initials: "DLVY",   hex: "#E1251B" },
  HAL:         { initials: "HAL",    hex: "#003876" },
  BEL:         { initials: "BEL",    hex: "#003876" },
  BHEL:        { initials: "BHEL",   hex: "#ED1C24" },
  SAIL:        { initials: "SAIL",   hex: "#003876" },
  NMDC:        { initials: "NMDC",   hex: "#7A1F2B" },
  NHPC:        { initials: "NHPC",   hex: "#0033A0" },
  SJVN:        { initials: "SJVN",   hex: "#0033A0" },
  IEX:         { initials: "IEX",    hex: "#00A651" },
  CONCOR:      { initials: "CONC",   hex: "#003876" },
  IGL:         { initials: "IGL",    hex: "#00A651" },
  MGL:         { initials: "MGL",    hex: "#00A651" },
  PETRONET:    { initials: "PLNG",   hex: "#F58220" },
  ADANIGREEN:  { initials: "ADANI",  hex: "#E31E24" },
  ADANIPOWER:  { initials: "ADANI",  hex: "#E31E24" },
  ADANIENSOL:  { initials: "ADANI",  hex: "#E31E24" },
  JINDALSTEL:  { initials: "JSPL",   hex: "#0B3861" },
  SHREECEM:    { initials: "SHREE",  hex: "#0B3861" },
  ACC:         { initials: "ACC",    hex: "#ED1C24" },
  RAMCOCEM:    { initials: "RAMCO",  hex: "#ED1C24" },
  POLYCAB:     { initials: "POLY",   hex: "#ED1C24" },
  ABB:         { initials: "ABB",    hex: "#FF000F" },
  CUMMINSIND:  { initials: "CMI",    hex: "#003876" },
  BOSCHLTD:    { initials: "BOSCH",  hex: "#ED1C24" },
  SRF:         { initials: "SRF",    hex: "#003DA5" },
  PIIND:       { initials: "PI",     hex: "#00563F" },
  ATGL:        { initials: "ATGL",   hex: "#E31E24" },
  INDIGO:      { initials: "6E",     hex: "#00205B" },
  TRENT:       { initials: "TRENT",  hex: "#1A1A2E" },
  ABFRL:       { initials: "ABFRL",  hex: "#6A1B9A" },
  PAGEIND:     { initials: "PAGE",   hex: "#003876" },
  VOLTAS:      { initials: "VOLT",   hex: "#003876" },
  WHIRLPOOL:   { initials: "WHIRL",  hex: "#0033A0" },
  CROMPTON:    { initials: "CROM",   hex: "#ED1C24" },
  DIXON:       { initials: "DIXON",  hex: "#003876" },
  KALYANKJIL:  { initials: "KJ",     hex: "#7A1F2B" },
  JUBLFOOD:    { initials: "JUBL",   hex: "#ED1C24" },
  SBICARD:     { initials: "SBI",    hex: "#2A5DB0" },
  ANGELONE:    { initials: "ANGEL",  hex: "#F58220" },
  CDSL:        { initials: "CDSL",   hex: "#003876" },
  BSE:         { initials: "BSE",    hex: "#003876" },
  MCX:         { initials: "MCX",    hex: "#003876" },
  HDFCAMC:     { initials: "HDFC",   hex: "#E31E24" },
  NAM:         { initials: "NIMF",   hex: "#C8102E" },
  UTIAMC:      { initials: "UTI",    hex: "#003DA5" },
  ABCAPITAL:   { initials: "ABC",    hex: "#6A1B9A" },
  PFIZER:      { initials: "PFE",    hex: "#0093D0" },
  GLAXO:       { initials: "GSK",    hex: "#F36633" },
  ABBOTINDIA:  { initials: "ABT",    hex: "#0057A8" },
  SANOFI:      { initials: "SNY",    hex: "#7A1FA2" },
  IPCALAB:     { initials: "IPCA",   hex: "#00563F" },
  LAURUSLABS:  { initials: "LAUR",   hex: "#00563F" },
  GLENMARK:    { initials: "GLENM",  hex: "#ED1C24" },
  NATCOPHARM:  { initials: "NATCO",  hex: "#00563F" },
  SUZLON:      { initials: "SZLN",   hex: "#00A651" },
  RVNL:        { initials: "RVNL",   hex: "#003876" },
  RAILTEL:     { initials: "RAIL",   hex: "#003876" },
  IRB:         { initials: "IRB",    hex: "#003876" },
  GMRAIRPORT:  { initials: "GMR",    hex: "#003876" },
  KPITTECH:    { initials: "KPIT",   hex: "#003DA5" },
  TATAELXSI:   { initials: "TATA",   hex: "#0B3861" },
  TATACOMM:    { initials: "TATA",   hex: "#0B3861" },
  TATAPOWER:   { initials: "TATA",   hex: "#0B3861" },
  TATACHEM:    { initials: "TATA",   hex: "#0B3861" },
  TATATECH:    { initials: "TATA",   hex: "#0B3861" },
  TIINDIA:     { initials: "TI",     hex: "#0B3861" },
  ASHOKLEY:    { initials: "AL",     hex: "#ED1C24" },
  TVSMOTOR:    { initials: "TVS",    hex: "#ED1C24" },
  BALKRISIND:  { initials: "BKT",    hex: "#ED1C24" },
  MRF:         { initials: "MRF",    hex: "#ED1C24" },
  APOLLOTYRE:  { initials: "APOLLO", hex: "#ED1C24" },
  EXIDEIND:    { initials: "EXIDE",  hex: "#003876" },
  IDEA:        { initials: "VI",     hex: "#EC1D46" },
  OIL:         { initials: "OIL",    hex: "#F58220" },
  HINDPETRO:   { initials: "HPCL",   hex: "#F58220" },
  CHAMBLFERT:  { initials: "CFCL",   hex: "#00563F" },
  COROMANDEL:  { initials: "CRIN",   hex: "#00563F" },
  UBL:         { initials: "UBL",    hex: "#003876" },
  RADICO:      { initials: "RAD",    hex: "#ED1C24" },
  EMAMILTD:    { initials: "EMAMI",  hex: "#ED1C24" },
  HONAUT:      { initials: "HON",    hex: "#E2231A" },
  THERMAX:     { initials: "TMX",    hex: "#003876" },
  KEI:         { initials: "KEI",    hex: "#003876" },
  ESCORTS:     { initials: "ESC",    hex: "#003876" },
  BHARATFORG:  { initials: "BF",     hex: "#003876" },
  MOTHERSON:   { initials: "MSUMI",  hex: "#003876" },
};

export function getStockMonogram(symbol?: string): StockMonogram | undefined {
  if (!symbol) return undefined;
  return STOCK_MONOGRAMS[symbol.trim().toUpperCase()];
}
