-- SIP buy/sell transaction log per investment — bounded by transaction volume rather than user
-- count, so (like stock_master/stock_transactions) a BIGINT identity PK is used instead of UUID.

CREATE TABLE sip_transactions (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    investment_id     UUID          NOT NULL REFERENCES investments(id) ON DELETE CASCADE,
    transaction_date  DATE          NOT NULL,
    amount            NUMERIC(18,2) NOT NULL,
    units             NUMERIC(18,4),
    nav               NUMERIC(18,4),
    transaction_type  VARCHAR(20)   DEFAULT 'BUY' NOT NULL,
    notes             VARCHAR(500),
    created_at        TIMESTAMPTZ   DEFAULT now() NOT NULL
);

CREATE INDEX idx_sip_investment ON sip_transactions (investment_id);
CREATE INDEX idx_sip_date       ON sip_transactions (transaction_date DESC);
