-- Individual stock buy/sell lots per investment — feeds the XIRR/gain-loss calculations.

CREATE TABLE stock_transactions (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    investment_id     UUID          NOT NULL REFERENCES investments(id) ON DELETE CASCADE,
    transaction_date  DATE          NOT NULL,
    transaction_type  VARCHAR(10)   DEFAULT 'BUY' NOT NULL,
    quantity          NUMERIC(14,4) NOT NULL,
    price_per_share   NUMERIC(14,4) NOT NULL,
    brokerage         NUMERIC(14,2) DEFAULT 0,
    notes             VARCHAR(500),
    created_at        TIMESTAMPTZ   DEFAULT now() NOT NULL
);

CREATE INDEX idx_stock_txn_investment ON stock_transactions (investment_id);
