-- Master list of NSE/BSE-listed securities (symbol search source) — bounded by total listed
-- securities (~thousands), not by user count, so a BIGINT sequence PK is appropriate here rather
-- than the UUID convention used for user-owned data.

CREATE TABLE stock_master (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol        VARCHAR(50)  NOT NULL,
    company_name  VARCHAR(300) NOT NULL,
    exchange      VARCHAR(10)  DEFAULT 'NSE' NOT NULL,
    isin          VARCHAR(20),
    series        VARCHAR(10),
    sector        VARCHAR(100),
    is_active     BOOLEAN      DEFAULT true NOT NULL,
    created_at    TIMESTAMPTZ  DEFAULT now() NOT NULL,
    updated_at    TIMESTAMPTZ  DEFAULT now() NOT NULL,
    CONSTRAINT uq_stock_master UNIQUE (symbol, exchange)
);

CREATE INDEX idx_sm_symbol  ON stock_master (symbol);
CREATE INDEX idx_sm_company ON stock_master (LOWER(company_name));
CREATE INDEX idx_sm_isin    ON stock_master (isin) WHERE isin IS NOT NULL;
